apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: bikesharingfeedbackapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bikesharingfeedbackapi
    spec:
      containers:
        - name: bikesharingfeedbackapi 
          image: builddemo.azurecr.io/bikesharingfeedbackapi 
          ports:
          - containerPort: 80