apiVersion: v1
kind: Service
metadata:
  name: {{ template "emailapi.fullname" . }}
  labels:
    app: {{ template "emailapi.name" . }}
    chart: {{ template "emailapi.chart" . }}
    release: "{{ .Values.ReleaseName  }}"
    heritage: "{{ .Values.ReleaseService }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "emailapi.name" . }}
    release: "{{ .Values.ReleaseName  }}"
