apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: bikesharingcampaign
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bikesharingcampaign
    spec:
      containers:
        - name: bikesharingcampaign 
          image: builddemo.azurecr.io/bikesharingcampaign 
          ports:
          - containerPort: 80