apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: bikesharingprofileapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bikesharingprofileapi
    spec:
      containers:
        - name: bikesharingprofileapi 
          image: builddemo.azurecr.io/bikesharingprofileapi 
          ports:
          - containerPort: 80