apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: bikesharingemailapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bikesharingemailapi
    spec:
      containers:
        - name: bikesharingemailapi 
          image: builddemo.azurecr.io/bikesharingemailapi 
          ports:
          - containerPort: 80